// FeelingsData.js

export const metNeedsFeelingsData = {
	Hopeful: [
		{ feeling: "Hopeful", meaning: "Feeling positive about future possibilities" },
		{ feeling: "Confident", meaning: "Trusting in one's own abilities or qualities" },
		{ feeling: "Grateful", meaning: "Appreciative of something received or experienced" },
		{ feeling: "Inspired", meaning: "Feeling mentally stimulated to act or create" },
		{ feeling: "Optimistic", meaning: "Expecting the best possible outcome" },
		{ feeling: "Trusting", meaning: "Willing to rely on someone or something" },
	],
	Joyful: [
		{ feeling: "Joyful", meaning: "Experiencing great pleasure and happiness" },
		{ feeling: "Excited", meaning: "Feeling eager or enthusiastic" },
		{ feeling: "Playful", meaning: "Full of fun and good humor" },
		{ feeling: "Happy", meaning: "Feeling or showing pleasure or contentment" },
		{ feeling: "Content", meaning: "Satisfied and at ease" },
		{ feeling: "Cheerful", meaning: "Noticeably happy and optimistic" },
		{ feeling: "Delighted", meaning: "Feeling great pleasure" },
		{ feeling: "Elated", meaning: "Exhilarated and extremely happy" },
	],
	Peaceful: [
		{ feeling: "Peaceful", meaning: "Free from disturbance; calm" },
		{ feeling: "Calm", meaning: "Not agitated; at rest" },
		{ feeling: "Serene", meaning: "Peaceful and untroubled" },
		{ feeling: "Relaxed", meaning: "Free from tension or anxiety" },
		{ feeling: "At ease", meaning: "Comfortable and untroubled" },
		{ feeling: "Centered", meaning: "Emotionally grounded and balanced" },
		{ feeling: "Relieved", meaning: "No longer feeling anxious or distressed" },
	],
	Proud: [
		{ feeling: "Proud", meaning: "Feeling deep pleasure or satisfaction from achievements" },
		{ feeling: "Empowered", meaning: "Feeling strong and in control of your life" },
		{ feeling: "Respected", meaning: "Regarded with admiration or esteem" },
		{ feeling: "Valued", meaning: "Recognized as important or appreciated" },
		{ feeling: "Acknowledged", meaning: "Recognized or validated" },
		{ feeling: "Appreciated", meaning: "Gratefully recognized" },
		{ feeling: "Honoured", meaning: "Held in high esteem" },
	],
	Engaged: [
		{ feeling: "Engaged", meaning: "Fully involved and interested" },
		{ feeling: "Interested", meaning: "Eager to learn or know more" },
		{ feeling: "Curious", meaning: "Eager to explore or understand" },
		{ feeling: "Absorbed", meaning: "Deeply engrossed or preoccupied" },
		{ feeling: "Stimulated", meaning: "Mentally or emotionally aroused" },
		{ feeling: "Intrigued", meaning: "Fascinated or captivated" },
	],
	Loving: [
		{ feeling: "Loving", meaning: "Full of love or strong affection" },
		{ feeling: "Caring", meaning: "Displaying kindness and concern" },
		{ feeling: "Affectionate", meaning: "Showing fondness or tenderness" },
		{ feeling: "Compassionate", meaning: "Showing deep sympathy and concern" },
		{ feeling: "Tender", meaning: "Gentle and kind" },
		{ feeling: "Warm", meaning: "Emotionally expressive and welcoming" },
		{ feeling: "Connected", meaning: "Emotionally bonded or in sync" },
	],
};

export const unmetNeedsFeelingsData = {
	Afraid: [
		{ feeling: "Afraid", meaning: "Feeling fear or anxiety" },
		{ feeling: "Anxious", meaning: "Worried and uneasy" },
		{ feeling: "Worried", meaning: "Troubled about potential problems" },
		{ feeling: "Apprehensive", meaning: "Fearful something bad may happen" },
		{ feeling: "Nervous", meaning: "Easily agitated or alarmed" },
		{ feeling: "Fearful", meaning: "Experiencing fear" },
		{ feeling: "Terrified", meaning: "Extremely scared" },
	],
	Angry: [
		{ feeling: "Angry", meaning: "Feeling strong displeasure or rage" },
		{ feeling: "Frustrated", meaning: "Feeling blocked or thwarted" },
		{ feeling: "Irritated", meaning: "Annoyed or slightly angry" },
		{ feeling: "Annoyed", meaning: "Bothered by something minor" },
		{ feeling: "Resentful", meaning: "Bitter due to feeling wronged" },
		{ feeling: "Enraged", meaning: "Very angry; furious" },
		{ feeling: "Furious", meaning: "Extremely angry" },
	],
	Sad: [
		{ feeling: "Sad", meaning: "Feeling sorrow or unhappiness" },
		{ feeling: "Disappointed", meaning: "Feeling let down" },
		{ feeling: "Hurt", meaning: "Emotionally wounded" },
		{ feeling: "Lonely", meaning: "Feeling socially isolated" },
		{ feeling: "Grieving", meaning: "Mourning a loss" },
		{ feeling: "Discouraged", meaning: "Losing confidence or enthusiasm" },
		{ feeling: "Heartbroken", meaning: "Deeply hurt emotionally" },
	],
	Confused: [
		{ feeling: "Confused", meaning: "Unable to think clearly" },
		{ feeling: "Unclear", meaning: "Lacking understanding or clarity" },
		{ feeling: "Puzzled", meaning: "Perplexed or confused" },
		{ feeling: "Perplexed", meaning: "Completely baffled" },
		{ feeling: "Disoriented", meaning: "Having lost sense of direction or clarity" },
		{ feeling: "Baffled", meaning: "Totally bewildered" },
		{ feeling: "Overwhelmed", meaning: "Burdened or overloaded emotionally" },
	],
	Embarrassed: [
		{ feeling: "Embarrassed", meaning: "Feeling self-conscious or awkward" },
		{ feeling: "Ashamed", meaning: "Feeling guilt or disgrace" },
		{ feeling: "Guilty", meaning: "Feeling responsible for wrongdoing" },
		{ feeling: "Self-conscious", meaning: "Overly aware of oneself" },
		{ feeling: "Humiliated", meaning: "Deeply embarrassed or ashamed" },
		{ feeling: "Insecure", meaning: "Lacking confidence or assurance" },
	],
	Tired: [
		{ feeling: "Tired", meaning: "In need of rest" },
		{ feeling: "Exhausted", meaning: "Extremely tired" },
		{ feeling: "Drained", meaning: "Depleted of energy" },
		{ feeling: "Fatigued", meaning: "Physically or mentally worn out" },
		{ feeling: "Weary", meaning: "Reluctant or tired due to overuse" },
		{ feeling: "Burned out", meaning: "Emotionally exhausted" },
		{ feeling: "Depleted", meaning: "Used up or exhausted" },
	],
	Disconnected: [
		{ feeling: "Disconnected", meaning: "Feeling separate or apart" },
		{ feeling: "Alienated", meaning: "Feeling isolated from others" },
		{ feeling: "Isolated", meaning: "Alone or separated from others" },
		{ feeling: "Numb", meaning: "Unable to feel emotionally" },
		{ feeling: "Unseen", meaning: "Feeling invisible or overlooked" },
		{ feeling: "Ignored", meaning: "Feeling deliberately disregarded" },
		{ feeling: "Unheard", meaning: "Feeling like your voice doesn't matter" },
	],
};
