// feelingsData.js

export const feelingsData = {
	"Feelings when needs are not met": {
		Afraid: [
			{ item: "Afraid", problem: "Experiencing fear or anxiety", status: "" },
			{ item: "Anxious", problem: "Worried or uneasy", status: "" },
			{ item: "Worried", problem: "Troubled about potential problems", status: "" },
			{ item: "Apprehensive", problem: "Uneasy or fearful about something", status: "" },
			{ item: "Nervous", problem: "Agitated or easily alarmed", status: "" },
			{ item: "Fearful", problem: "Feeling afraid something bad will happen", status: "" },
			{ item: "Terrified", problem: "Extremely afraid", status: "" },
		],
		Angry: [
			{ item: "Angry", problem: "Strong feeling of displeasure or hostility", status: "" },
			{ item: "Frustrated", problem: "Upset because of inability to change or achieve something", status: "" },
			{ item: "Irritated", problem: "Mildly angry or annoyed", status: "" },
			{ item: "Annoyed", problem: "Slightly angry", status: "" },
			{ item: "Resentful", problem: "Bitter about being treated unfairly", status: "" },
			{ item: "Enraged", problem: "Very angry or furious", status: "" },
			{ item: "Furious", problem: "Extremely angry", status: "" },
		],
		Sad: [
			{ item: "Sad", problem: "Feeling sorrow or unhappiness", status: "" },
			{ item: "Disappointed", problem: "Let down by unmet expectations", status: "" },
			{ item: "Hurt", problem: "Emotionally pained", status: "" },
			{ item: "Lonely", problem: "Feeling alone or disconnected", status: "" },
			{ item: "Grieving", problem: "Experiencing sorrow due to loss", status: "" },
			{ item: "Discouraged", problem: "Losing confidence or hope", status: "" },
			{ item: "Heartbroken", problem: "Devastated by emotional loss", status: "" },
		],
		Confused: [
			{ item: "Confused", problem: "Unable to think clearly or understand", status: "" },
			{ item: "Unclear", problem: "Lacking clarity or understanding", status: "" },
			{ item: "Bewildered", problem: "Stunned at everyone else's incomptence", status: "" },
			{ item: "Puzzled", problem: "Baffled or uncertain", status: "" },
			{ item: "Perplexed", problem: "Completely baffled", status: "" },
			{ item: "Disoriented", problem: "Lost or confused about surroundings or thoughts", status: "" },
			{ item: "Baffled", problem: "Totally confused or perplexed", status: "" },
			{ item: "Overwhelmed", problem: "Overpowered by emotions or tasks", status: "" },
		],
		Embarrassed: [
			{ item: "Embarrassed", problem: "Feeling self-conscious or awkward", status: "" },
			{ item: "Ashamed", problem: "Feeling guilt or disgrace", status: "" },
			{ item: "Guilty", problem: "Feeling responsible for wrongdoing", status: "" },
			{ item: "Self-conscious", problem: "Uncomfortably aware of self", status: "" },
			{ item: "Humiliated", problem: "Deeply embarrassed or shamed", status: "" },
			{ item: "Insecure", problem: "Lacking confidence or assurance", status: "" },
		],
		Tired: [
			{ item: "Tired", problem: "Needing rest", status: "" },
			{ item: "Exhausted", problem: "Completely drained of energy", status: "" },
			{ item: "Drained", problem: "Lacking energy or motivation", status: "" },
			{ item: "Fatigued", problem: "Very tired and worn out", status: "" },
			{ item: "Weary", problem: "Tired from work or stress", status: "" },
			{ item: "Burned out", problem: "Emotionally exhausted due to prolonged stress", status: "" },
			{ item: "Depleted", problem: "Used up or empty of energy", status: "" },
		],
		Disconnected: [
			{ item: "Disconnected", problem: "Emotionally detached", status: "" },
			{ item: "Alienated", problem: "Feeling isolated from others", status: "" },
			{ item: "Isolated", problem: "Cut off from others", status: "" },
			{ item: "Numb", problem: "Unable to feel or express emotions", status: "" },
			{ item: "Unseen", problem: "Feeling invisible to others", status: "" },
			{ item: "Ignored", problem: "Feeling neglected or dismissed", status: "" },
			{ item: "Unheard", problem: "Not listened to or acknowledged", status: "" },
		],
	},

	"Faux Feelings": {
		"Judgments of Others": [
			{
				item: "abandoned",
				problem: "Implies someone did something wrong by leaving",
				thought: "You're having the thought that someone left you when you really needed them",
				suggestedFeelings: ["terrified", "hurt", "bewildered", "sad", "frightened", "lonely"],
				suggestedNeeds: [
					"nurturing",
					"connection",
					"belonging",
					"support",
					"caring",
					"companionship",
					"emotional safety",
				],
				status: "",
			},
			{
				item: "abused",
				problem: "Describes an action, not a feeling — needs protection and care",
				thought: "You're having the thought that someone treated you in a cruel or violating way",
				suggestedFeelings: ["frightened", "confused", "overwhelmed", "hurt"],
				suggestedNeeds: [
					"caring",
					"nurturing",
					"support",
					"emotional safety",
					"physical safety",
					"consideration",
					"mattering",
					"trust",
				],
				status: "",
			},
			{
				item: "attacked",
				problem: "Assumes hostile intent, not just how you feel",
				thought: "You're having the thought that someone came at you with hostility or blame",
				suggestedFeelings: ["scared", "vulnerable", "angry", "defensive", "shaky"],
				suggestedNeeds: ["safety", "respect", "understanding", "autonomy", "emotional safety", "space"],
				status: "",
			},
			{
				item: "belittled",
				problem: "Judges someone else's action as putting you down",
				thought: "You're having the thought that someone is putting you down or making you feel small",
				suggestedFeelings: ["hurt", "tense", "distressed", "ashamed", "angry"],
				suggestedNeeds: [
					"respect",
					"autonomy",
					"visibility",
					"understanding",
					"acknowledgement",
					"appreciation",
					"dignity",
				],
				status: "",
			},
			{
				item: "betrayed",
				problem: "Focuses on someone else's broken promise or loyalty",
				thought: "You're having the thought that someone broke your trust or turned on you",
				suggestedFeelings: ["hurt", "scared", "disappointed", "devastated"],
				suggestedNeeds: [
					"trust",
					"dependability",
					"honesty",
					"honour",
					"commitment",
					"clarity",
					"emotional safety",
				],
				status: "",
			},
			{
				item: "blamed",
				problem: "Points to being accused, rather than how you feel",
				thought: "You're having the thought that you're being unfairly accused or held responsible",
				suggestedFeelings: ["scared", "confused", "bewildered", "hurt", "angry"],
				suggestedNeeds: ["accountability", "fairness", "clarity", "understanding", "trust"],
				status: "",
			},
			{
				item: "bullied",
				problem: "Describes being targeted or controlled by another",
				thought: "You're having the thought that someone is intimidating or trying to control you",
				suggestedFeelings: ["scared", "powerless", "anxious", "angry", "hopeless"],
				suggestedNeeds: ["autonomy", "choice", "safety", "consideration", "respect", "empowerment"],
				status: "",
			},
			{
				item: "cheated",
				problem: "Judges unfair treatment by another",
				thought: "You're having the thought that someone took advantage of you or broke an agreement",
				suggestedFeelings: ["hurt", "angry", "disappointed", "disrespected"],
				suggestedNeeds: ["honesty", "fairness", "justice", "trust", "reliability"],
				status: "",
			},
			{
				item: "coerced",
				problem: "Assumes you were forced against your will",
				thought: "You're having the thought that someone pressured or forced you into something",
				suggestedFeelings: ["afraid", "angry", "trapped", "resentful"],
				suggestedNeeds: ["autonomy", "choice", "freedom", "respect", "safety"],
				status: "",
			},
			{
				item: "caged",
				problem: "Evokes restriction without naming the feeling",
				thought: "You're having the thought that you're being trapped or restricted against your will",
				suggestedFeelings: ["anxious", "frustrated", "desperate"],
				suggestedNeeds: ["freedom", "space", "autonomy", "movement", "choice"],
				status: "",
			},
		],
		"Blame-Oriented Phrases": [
			{
				item: "criticized",
				problem: "Refers to what someone did, not how you felt",
				thought: "You're having the thought that someone is judging or finding fault with you",
				suggestedFeelings: ["defensive", "hurt", "ashamed", "angry"],
				suggestedNeeds: ["understanding", "acknowledgement", "respect", "appreciation", "empathy"],
				status: "",
			},
			{
				item: "ignored",
				problem: "Centers on others' behaviour, not your emotional state",
				thought: "You're having the thought that your presence or needs don’t matter to someone",
				suggestedFeelings: ["lonely", "hurt", "frustrated", "sad", "angry"],
				suggestedNeeds: ["attention", "connection", "acknowledgement", "mattering", "inclusion"],
				status: "",
			},
			{
				item: "manipulated",
				problem: "Assumes bad intent, rather than expressing distrust or confusion",
				thought: "You're having the thought that someone is trying to control or deceive you",
				suggestedFeelings: ["confused", "uneasy", "angry", "powerless"],
				suggestedNeeds: ["clarity", "honesty", "autonomy", "respect", "trust", "safety"],
				status: "",
			},
			{
				item: "neglected",
				problem: "Implies wrongdoing or failure by others",
				thought: "You're having the thought that someone failed to care for or attend to you",
				suggestedFeelings: ["hurt", "lonely", "resentful", "empty"],
				suggestedNeeds: ["care", "attention", "support", "nurturing", "belonging", "value", "reliability"],
				status: "",
			},
			{
				item: "rejected",
				problem: "Focuses on what someone did, not your feeling",
				thought: "You're having the thought that you're being pushed away or excluded",
				suggestedFeelings: ["sad", "hurt", "ashamed", "insecure"],
				suggestedNeeds: ["acceptance", "belonging", "connection", "love", "self-acceptance"],
				status: "",
			},
		],
		"Diagnosis and Labels": [
			{
				item: "triggered",
				problem: "Refers to a reaction, not the emotions it brings up",
				thought: "You're having the thought that something just set off a big emotional reaction",
				suggestedFeelings: ["scared", "ashamed", "angry", "overwhelmed"],
				suggestedNeeds: ["safety", "healing", "self-connection", "emotional support", "stability"],
				status: "",
			},
			{
				item: "traumatized",
				problem: "Describes a state, not a current feeling",
				thought: "You're having the thought that you're overwhelmed or re-experiencing a past wound",
				suggestedFeelings: ["frozen", "terrified", "disconnected", "numb", "overwhelmed"],
				suggestedNeeds: ["safety", "healing", "emotional care", "trust", "reassurance", "stability"],
				status: "",
			},
			{
				item: "depressed",
				problem: "Often used as a diagnosis — try describing the sensations or emotions instead",
				thought: "You're having the thought that you’re stuck in a deep, dark place you can’t get out of",
				suggestedFeelings: ["numb", "sad", "hopeless", "drained", "disconnected", "tired"],
				suggestedNeeds: ["meaning", "connection", "purpose", "rest", "support", "emotional safety", "hope"],
				status: "",
			},
			{
				item: "anxious",
				problem: "Can be vague or clinical — try describing the underlying fear or tension",
				thought: "You're having the thought that something bad might happen and you won’t be able to handle it",
				suggestedFeelings: ["nervous", "worried", "fearful", "tense", "jittery", "panicked"],
				suggestedNeeds: ["predictability", "reassurance", "support", "safety", "trust", "rest"],
				status: "",
			},
		],
		"Judgments of Self": [
			{
				item: "inadequate",
				problem: "A self-judgment — look for feelings like ashamed or discouraged",
				thought: "You're having the thought that you're not good enough or falling short",
				suggestedFeelings: ["ashamed", "discouraged", "insecure", "guilty"],
				suggestedNeeds: [
					"competence",
					"growth",
					"encouragement",
					"acknowledgement",
					"self-worth",
					"understanding",
				],
				status: "",
			},
			{
				item: "unworthy",
				problem: "A belief about your value, not a feeling",
				thought: "You're having the thought that you don't deserve love, care, or respect",
				suggestedFeelings: ["despairing", "ashamed", "disconnected", "numb"],
				suggestedNeeds: [
					"self-acceptance",
					"love",
					"belonging",
					"mattering",
					"contribution",
					"spiritual connection",
				],
				status: "",
			},
			{
				item: "unlovable",
				problem: "Judgment of self-worth, often masking grief or shame",
				thought: "You're having the thought that there's something about you that makes you impossible to love",
				suggestedFeelings: ["ashamed", "despairing", "lonely", "hopeless"],
				suggestedNeeds: ["love", "acceptance", "connection", "healing", "self-worth", "empathy"],
				status: "",
			},
			{
				item: "incompetent",
				problem: "Self-evaluation instead of naming fear, shame, or discouragement",
				thought: "You're having the thought that you're incapable or bound to mess things up",
				suggestedFeelings: ["ashamed", "embarrassed", "frustrated", "helpless"],
				suggestedNeeds: ["competence", "growth", "support", "patience", "acknowledgement"],
				status: "",
			},
		],
	},

	"Feelings when needs are met": {
		Hopeful: [
			{ item: "Hopeful", problem: "Looking to the future with optimism", status: "" },
			{ item: "Confident", problem: "Trusting in one’s abilities or qualities", status: "" },
			{ item: "Grateful", problem: "Appreciative of benefits received", status: "" },
			{ item: "Inspired", problem: "Mentally stimulated to do or feel something", status: "" },
			{ item: "Optimistic", problem: "Expecting the best possible outcome", status: "" },
			{ item: "Trusting", problem: "Willing to rely on others or situations", status: "" },
		],
		Joyful: [
			{ item: "Joyful", problem: "Feeling great happiness", status: "" },
			{ item: "Excited", problem: "Eager and enthusiastic", status: "" },
			{ item: "Playful", problem: "Light-hearted and fun-loving", status: "" },
			{ item: "Happy", problem: "Generally content and pleased", status: "" },
			{ item: "Content", problem: "Satisfied and at peace", status: "" },
			{ item: "Cheerful", problem: "Noticeably happy and optimistic", status: "" },
			{ item: "Delighted", problem: "Highly pleased", status: "" },
			{ item: "Elated", problem: "Ecstatically happy", status: "" },
		],
		Peaceful: [
			{ item: "Peaceful", problem: "Free from disturbance or conflict", status: "" },
			{ item: "Calm", problem: "Free from agitation or excitement", status: "" },
			{ item: "Serene", problem: "Peaceful and untroubled", status: "" },
			{ item: "Relaxed", problem: "Free from tension or anxiety", status: "" },
			{ item: "At ease", problem: "Comfortable and untroubled", status: "" },
			{ item: "Centered", problem: "Balanced and grounded", status: "" },
			{ item: "Relieved", problem: "Freed from distress or discomfort", status: "" },
		],
		Proud: [
			{ item: "Proud", problem: "Feeling deep satisfaction with achievements", status: "" },
			{ item: "Empowered", problem: "Feeling capable and in control", status: "" },
			{ item: "Respected", problem: "Regarded with honor and esteem", status: "" },
			{ item: "Valued", problem: "Recognized as important or worthwhile", status: "" },
			{ item: "Acknowledged", problem: "Noticed or affirmed", status: "" },
			{ item: "Appreciated", problem: "Seen and valued for contribution", status: "" },
			{ item: "Honoured", problem: "Treated with high respect", status: "" },
		],
		Engaged: [
			{ item: "Engaged", problem: "Involved and absorbed in the moment", status: "" },
			{ item: "Interested", problem: "Mentally engaged and curious", status: "" },
			{ item: "Curious", problem: "Eager to know or learn", status: "" },
			{ item: "Absorbed", problem: "Deeply engaged or immersed", status: "" },
			{ item: "Stimulated", problem: "Mentally or emotionally aroused", status: "" },
			{ item: "Intrigued", problem: "Fascinated and wanting to know more", status: "" },
		],
		Loving: [
			{ item: "Loving", problem: "Full of love and affection", status: "" },
			{ item: "Caring", problem: "Showing concern or kindness", status: "" },
			{ item: "Affectionate", problem: "Demonstrating fondness", status: "" },
			{ item: "Compassionate", problem: "Feeling and showing sympathy and concern", status: "" },
			{ item: "Tender", problem: "Gentle and kind", status: "" },
			{ item: "Warm", problem: "Expressing affection and kindness", status: "" },
			{ item: "Connected", problem: "Feeling close to others or something meaningful", status: "" },
		],
	},
};
