// FeelingsData.js

export const feelingsData = {
	"Feelings when needs are met": {
		Hopeful: [
			{ item: "Hopeful", meaning: "Looking to the future with optimism" },
			{ item: "Confident", meaning: "Trusting in one’s abilities or qualities" },
			{ item: "Grateful", meaning: "Appreciative of benefits received" },
			{ item: "Inspired", meaning: "Mentally stimulated to do or feel something" },
			{ item: "Optimistic", meaning: "Expecting the best possible outcome" },
			{ item: "Trusting", meaning: "Willing to rely on others or situations" },
		],
		Joyful: [
			{ item: "Joyful", meaning: "Feeling great happiness" },
			{ item: "Excited", meaning: "Eager and enthusiastic" },
			{ item: "Playful", meaning: "Light-hearted and fun-loving" },
			{ item: "Happy", meaning: "Generally content and pleased" },
			{ item: "Content", meaning: "Satisfied and at peace" },
			{ item: "Cheerful", meaning: "Noticeably happy and optimistic" },
			{ item: "Delighted", meaning: "Highly pleased" },
			{ item: "Elated", meaning: "Ecstatically happy" },
		],
		Peaceful: [
			{ item: "Peaceful", meaning: "Free from disturbance or conflict" },
			{ item: "Calm", meaning: "Free from agitation or excitement" },
			{ item: "Serene", meaning: "Peaceful and untroubled" },
			{ item: "Relaxed", meaning: "Free from tension or anxiety" },
			{ item: "At ease", meaning: "Comfortable and untroubled" },
			{ item: "Centered", meaning: "Balanced and grounded" },
			{ item: "Relieved", meaning: "Freed from distress or discomfort" },
		],
		Proud: [
			{ item: "Proud", meaning: "Feeling deep satisfaction with achievements" },
			{ item: "Empowered", meaning: "Feeling capable and in control" },
			{ item: "Respected", meaning: "Regarded with honor and esteem" },
			{ item: "Valued", meaning: "Recognized as important or worthwhile" },
			{ item: "Acknowledged", meaning: "Noticed or affirmed" },
			{ item: "Appreciated", meaning: "Seen and valued for contribution" },
			{ item: "Honoured", meaning: "Treated with high respect" },
		],
		Engaged: [
			{ item: "Engaged", meaning: "Involved and absorbed in the moment" },
			{ item: "Interested", meaning: "Mentally engaged and curious" },
			{ item: "Curious", meaning: "Eager to know or learn" },
			{ item: "Absorbed", meaning: "Deeply engaged or immersed" },
			{ item: "Stimulated", meaning: "Mentally or emotionally aroused" },
			{ item: "Intrigued", meaning: "Fascinated and wanting to know more" },
		],
		Loving: [
			{ item: "Loving", meaning: "Full of love and affection" },
			{ item: "Caring", meaning: "Showing concern or kindness" },
			{ item: "Affectionate", meaning: "Demonstrating fondness" },
			{ item: "Compassionate", meaning: "Feeling and showing sympathy and concern" },
			{ item: "Tender", meaning: "Gentle and kind" },
			{ item: "Warm", meaning: "Expressing affection and kindness" },
			{ item: "Connected", meaning: "Feeling close to others or something meaningful" },
		],
	},

	"Feelings when needs are not met": {
		Afraid: [
			{ item: "Afraid", meaning: "Experiencing fear or anxiety" },
			{ item: "Anxious", meaning: "Worried or uneasy" },
			{ item: "Worried", meaning: "Troubled about potential problems" },
			{ item: "Apprehensive", meaning: "Uneasy or fearful about something" },
			{ item: "Nervous", meaning: "Agitated or easily alarmed" },
			{ item: "Fearful", meaning: "Feeling afraid something bad will happen" },
			{ item: "Terrified", meaning: "Extremely afraid" },
		],
		Angry: [
			{ item: "Angry", meaning: "Strong feeling of displeasure or hostility" },
			{ item: "Frustrated", meaning: "Upset because of inability to change or achieve something" },
			{ item: "Irritated", meaning: "Mildly angry or annoyed" },
			{ item: "Annoyed", meaning: "Slightly angry" },
			{ item: "Resentful", meaning: "Bitter about being treated unfairly" },
			{ item: "Enraged", meaning: "Very angry or furious" },
			{ item: "Furious", meaning: "Extremely angry" },
		],
		Sad: [
			{ item: "Sad", meaning: "Feeling sorrow or unhappiness" },
			{ item: "Disappointed", meaning: "Let down by unmet expectations" },
			{ item: "Hurt", meaning: "Emotionally pained" },
			{ item: "Lonely", meaning: "Feeling alone or disconnected" },
			{ item: "Grieving", meaning: "Experiencing sorrow due to loss" },
			{ item: "Discouraged", meaning: "Losing confidence or hope" },
			{ item: "Heartbroken", meaning: "Devastated by emotional loss" },
		],
		Confused: [
			{ item: "Confused", meaning: "Unable to think clearly or understand" },
			{ item: "Unclear", meaning: "Lacking clarity or understanding" },
			{ item: "Puzzled", meaning: "Baffled or uncertain" },
			{ item: "Perplexed", meaning: "Completely baffled" },
			{ item: "Disoriented", meaning: "Lost or confused about surroundings or thoughts" },
			{ item: "Baffled", meaning: "Totally confused or perplexed" },
			{ item: "Overwhelmed", meaning: "Overpowered by emotions or tasks" },
		],
		Embarrassed: [
			{ item: "Embarrassed", meaning: "Feeling self-conscious or awkward" },
			{ item: "Ashamed", meaning: "Feeling guilt or disgrace" },
			{ item: "Guilty", meaning: "Feeling responsible for wrongdoing" },
			{ item: "Self-conscious", meaning: "Uncomfortably aware of self" },
			{ item: "Humiliated", meaning: "Deeply embarrassed or shamed" },
			{ item: "Insecure", meaning: "Lacking confidence or assurance" },
		],
		Tired: [
			{ item: "Tired", meaning: "Needing rest" },
			{ item: "Exhausted", meaning: "Completely drained of energy" },
			{ item: "Drained", meaning: "Lacking energy or motivation" },
			{ item: "Fatigued", meaning: "Very tired and worn out" },
			{ item: "Weary", meaning: "Tired from work or stress" },
			{ item: "Burned out", meaning: "Emotionally exhausted due to prolonged stress" },
			{ item: "Depleted", meaning: "Used up or empty of energy" },
		],
		Disconnected: [
			{ item: "Disconnected", meaning: "Emotionally detached" },
			{ item: "Alienated", meaning: "Feeling isolated from others" },
			{ item: "Isolated", meaning: "Cut off from others" },
			{ item: "Numb", meaning: "Unable to feel or express emotions" },
			{ item: "Unseen", meaning: "Feeling invisible to others" },
			{ item: "Ignored", meaning: "Feeling neglected or dismissed" },
			{ item: "Unheard", meaning: "Not listened to or acknowledged" },
		],
	},
};
