const needsData = {
	"Subsistence and Security": {
		"Physical sustenance": [
			{ item: "Air", meaning: "Clean air to breathe" },
			{ item: "Food", meaning: "Nourishing and satisfying meals" },
			{ item: "Health", meaning: "Physical well-being" },
			{ item: "Movement", meaning: "Freedom to move and be active" },
			{ item: "Physical Safety", meaning: "Freedom from physical harm" },
			{ item: "Rest / sleep", meaning: "Deep rest and renewal" },
			{ item: "Shelter", meaning: "Safe and secure housing" },
			{ item: "Touch", meaning: "Comforting physical contact" },
			{ item: "Water", meaning: "Clean water for drinking and hygiene" },
		],
		Security: [
			{ item: "Consistency", meaning: "Predictability and reliability" },
			{ item: "Order/Structure", meaning: "Clarity and organization" },
			{ item: "Peace (external)", meaning: "Safety from external conflict" },
			{ item: "Peace of mind", meaning: "Freedom from internal turmoil" },
			{ item: "Protection", meaning: "Being guarded from harm" },
			{ item: "Safety (emotional)", meaning: "Freedom to be emotionally vulnerable" },
			{ item: "Stability", meaning: "Steadiness in life circumstances" },
			{ item: "Trusting", meaning: "Confidence in people and systems" },
		],
	},

	Connection: {
		Affection: [
			{ item: "Appreciation", meaning: "Being seen and valued" },
			{ item: "Attention", meaning: "Being genuinely noticed" },
			{ item: "Closeness", meaning: "Emotional and/or physical intimacy" },
			{ item: "Companionship", meaning: "Enjoying life with others" },
			{ item: "Harmony", meaning: "Cooperation and mutual support" },
			{ item: "Intimacy", meaning: "Mutual vulnerability and closeness" },
			{ item: "Love", meaning: "Unconditional acceptance and care" },
			{ item: "Nurturing", meaning: "Care that supports growth and healing" },
			{ item: "Sexual expression", meaning: "Authentic physical intimacy" },
			{ item: "Support", meaning: "Practical or emotional backing" },
			{ item: "Tenderness", meaning: "Gentle, caring touch or tone" },
			{ item: "Warmth", meaning: "A sense of friendliness and care" },
		],
		"To matter": [
			{ item: "Acceptance", meaning: "Welcomed just as I am" },
			{ item: "Care", meaning: "Concern for my well-being" },
			{ item: "Compassion", meaning: "Understanding and warmth in response to suffering" },
			{ item: "Consideration", meaning: "Having my needs factored in" },
			{ item: "Empathy", meaning: "Emotional resonance and understanding" },
			{ item: "Respect", meaning: "Being valued and honored" },
			{ item: "To be heard, seen", meaning: "Fully acknowledged in experience" },
			{ item: "To be known, understood", meaning: "Deep recognition of who I am" },
			{ item: "To be trusted", meaning: "Confidence placed in me" },
			{ item: "Understanding others", meaning: "Being able to grasp others’ experience" },
			{ item: "Mutual Recognition", meaning: "Seeing and being seen by another" },
			{ item: "Kindness", meaning: "Gentle and benevolent care" },
		],
		Community: [
			{ item: "Belonging", meaning: "Feeling part of something" },
			{ item: "Communication", meaning: "Sharing and receiving information" },
			{ item: "Cooperation", meaning: "Working together toward common goals" },
			{ item: "Equality", meaning: "Equal worth and rights for all" },
			{ item: "Inclusion", meaning: "Being actively welcomed" },
			{ item: "Mutuality", meaning: "Reciprocal give and take" },
			{ item: "Participation", meaning: "Being involved and engaged" },
			{ item: "Partnership", meaning: "Collaborative and shared efforts" },
			{ item: "Self-expression", meaning: "Freedom to express who I am" },
			{ item: "Sharing", meaning: "Mutual giving and receiving" },
		],
	},

	Meaning: {
		"Sense of self": [
			{ item: "Authenticity", meaning: "Being true to myself" },
			{ item: "Competence", meaning: "Feeling capable and skilled" },
			{ item: "Creativity", meaning: "Expressing imagination and originality" },
			{ item: "Dignity", meaning: "Inherent worth and self-respect" },
			{ item: "Growth", meaning: "Development and evolution" },
			{ item: "Healing", meaning: "Moving toward wholeness" },
			{ item: "Honesty", meaning: "Telling and facing the truth" },
			{ item: "Integrity", meaning: "Living in alignment with values" },
			{ item: "Self-acceptance", meaning: "Welcoming all parts of myself" },
			{ item: "Self-care", meaning: "Tending to my own needs" },
			{ item: "Self-connection", meaning: "Awareness of inner experience" },
			{ item: "Self-knowledge", meaning: "Understanding myself" },
			{ item: "Self-realization", meaning: "Becoming who I am meant to be" },
			{ item: "Mattering to myself", meaning: "Recognizing my own value" },
		],
		Understanding: [
			{ item: "Awareness", meaning: "Conscious presence" },
			{ item: "Clarity", meaning: "Clear thinking and perception" },
			{ item: "Discovery", meaning: "Finding or uncovering something new" },
			{ item: "Learning", meaning: "Gaining knowledge or insight" },
			{ item: "Making sense of life", meaning: "Understanding the bigger picture" },
			{ item: "Stimulation", meaning: "Mental engagement and interest" },
		],
		Meaning: [
			{ item: "Challenge", meaning: "Opportunities to stretch and grow" },
			{ item: "Aliveness", meaning: "Feeling fully vibrant and present" },
			{ item: "Consciousness", meaning: "Deep awareness of self and life" },
			{ item: "Contribution", meaning: "Making a difference" },
			{ item: "Effectiveness", meaning: "Capacity to bring about change" },
			{ item: "Exploration", meaning: "Willingness to investigate and try" },
			{ item: "Integration", meaning: "Wholeness and coherence" },
			{ item: "Purpose", meaning: "Having meaningful direction" },
		],
		Transcendence: [
			{ item: "Beauty", meaning: "Appreciating harmony and elegance" },
			{ item: "Celebration of life", meaning: "Honoring what’s precious" },
			{ item: "Communion", meaning: "Deep spiritual or emotional connection" },
			{ item: "Faith", meaning: "Trust in something greater" },
			{ item: "Flow", meaning: "Being fully absorbed in the moment" },
			{ item: "Hope", meaning: "Belief in possibilities" },
			{ item: "Inspiration", meaning: "Being uplifted into vision or action" },
			{ item: "Mourning", meaning: "Honoring loss with care" },
			{ item: "Peace (internal)", meaning: "Calm within" },
			{ item: "Presence", meaning: "Fully here and now" },
		],
	},

	Freedom: {
		Autonomy: [
			{ item: "Choice", meaning: "Freedom to decide" },
			{ item: "Ease", meaning: "Freedom from strain or effort" },
			{ item: "Independence", meaning: "Self-reliance and agency" },
			{ item: "Power", meaning: "Ability to influence" },
			{ item: "Self-responsiblity", meaning: "Owning my own choices" },
			{ item: "Space", meaning: "Room to be and act" },
			{ item: "Spontaneity", meaning: "Freedom to act in the moment" },
		],
		"Leisure/Relaxation": [
			{ item: "Humour", meaning: "Lightness and laughter" },
			{ item: "Joy", meaning: "Delight and happiness" },
			{ item: "Play", meaning: "Fun, imagination and creativity" },
			{ item: "Pleasure", meaning: "Enjoyable sensations or experiences" },
			{ item: "Rejuvenation", meaning: "Feeling refreshed and renewed" },
		],
	},
};

export default needsData;
