const needsData = {
	"Subsistence and Security": {
		"Physical sustenance": [
			{ item: "Air", meaning: "Clean air to breathe", status: "" },
			{ item: "Food", meaning: "Nourishing and satisfying meals", status: "" },
			{ item: "Health", meaning: "Physical well-being", status: "" },
			{ item: "Movement", meaning: "Freedom to move and be active", status: "" },
			{ item: "Physical Safety", meaning: "Freedom from physical harm", status: "" },
			{ item: "Rest / sleep", meaning: "Deep rest and renewal", status: "" },
			{ item: "Shelter", meaning: "Safe and secure housing", status: "" },
			{ item: "Touch", meaning: "Comforting physical contact", status: "" },
			{ item: "Water", meaning: "Clean water for drinking and hygiene", status: "" },
		],
		Security: [
			{ item: "Consistency", meaning: "Predictability and reliability", status: "" },
			{ item: "Order/Structure", meaning: "Clarity and organization", status: "" },
			{ item: "Peace (external)", meaning: "Safety from external conflict", status: "" },
			{ item: "Peace of mind", meaning: "Freedom from internal turmoil", status: "" },
			{ item: "Protection", meaning: "Being guarded from harm", status: "" },
			{ item: "Safety (emotional)", meaning: "Freedom to be emotionally vulnerable", status: "" },
			{ item: "Stability", meaning: "Steadiness in life circumstances", status: "" },
			{ item: "Trusting", meaning: "Confidence in people and systems", status: "" },
		],
	},

	Connection: {
		Affection: [
			{ item: "Affection", meaning: "Expressions of emotional warmth and connection", status: "" },
			{ item: "Appreciation", meaning: "Being seen and valued", status: "" },
			{ item: "Attention", meaning: "Being genuinely noticed", status: "" },
			{ item: "Closeness", meaning: "Emotional and/or physical intimacy", status: "" },
			{ item: "Companionship", meaning: "Enjoying life with others", status: "" },
			{ item: "Harmony", meaning: "Cooperation and mutual support", status: "" },
			{ item: "Intimacy", meaning: "Mutual vulnerability and closeness", status: "" },
			{ item: "Love", meaning: "Unconditional acceptance and care", status: "" },
			{ item: "Nurturing", meaning: "Care that supports growth and healing", status: "" },
			{ item: "Sexual expression", meaning: "Authentic physical intimacy", status: "" },
			{ item: "Support", meaning: "Practical or emotional backing", status: "" },
			{ item: "Tenderness", meaning: "Gentle, caring touch or tone", status: "" },
			{ item: "Warmth", meaning: "A sense of friendliness and care", status: "" },
		],
		"To matter": [
			{ item: "To matter", meaning: "To know that I am valued", status: "" },
			{ item: "Acceptance", meaning: "Welcomed just as I am", status: "" },
			{ item: "Care", meaning: "Concern for my well-being", status: "" },
			{ item: "Compassion", meaning: "Understanding and warmth in response to suffering", status: "" },
			{ item: "Consideration", meaning: "Having my needs factored in", status: "" },
			{ item: "Empathy", meaning: "Emotional resonance and understanding", status: "" },
			{ item: "Respect", meaning: "Being valued and honored", status: "" },
			{ item: "To be heard, seen", meaning: "Fully acknowledged in experience", status: "" },
			{ item: "To be known, understood", meaning: "Deep recognition of who I am", status: "" },
			{ item: "To be trusted", meaning: "Confidence placed in me", status: "" },
			{ item: "Understanding others", meaning: "Being able to grasp others’ experience", status: "" },
			{ item: "Mutual Recognition", meaning: "Seeing and being seen by another", status: "" },
			{ item: "Kindness", meaning: "Gentle and benevolent care", status: "" },
		],
		Community: [
			{ item: "Community", meaning: "Belonging to a group", status: "" },
			{ item: "Belonging", meaning: "Feeling part of something", status: "" },
			{ item: "Communication", meaning: "Sharing and receiving information", status: "" },
			{ item: "Cooperation", meaning: "Working together toward common goals", status: "" },
			{ item: "Equality", meaning: "Equal worth and rights for all", status: "" },
			{ item: "Inclusion", meaning: "Being actively welcomed", status: "" },
			{ item: "Mutuality", meaning: "Reciprocal give and take", status: "" },
			{ item: "Participation", meaning: "Being involved and engaged", status: "" },
			{ item: "Partnership", meaning: "Collaborative and shared efforts", status: "" },
			{ item: "Self-expression", meaning: "Freedom to express who I am", status: "" },
			{ item: "Sharing", meaning: "Mutual giving and receiving", status: "" },
		],
	},

	Meaning: {
		"Sense of self": [
			{ item: "Authenticity", meaning: "Being true to myself", status: "" },
			{ item: "Competence", meaning: "Feeling capable and skilled", status: "" },
			{ item: "Creativity", meaning: "Expressing imagination and originality", status: "" },
			{ item: "Dignity", meaning: "Inherent worth and self-respect", status: "" },
			{ item: "Growth", meaning: "Development and evolution", status: "" },
			{ item: "Healing", meaning: "Moving toward wholeness", status: "" },
			{ item: "Honesty", meaning: "Telling and facing the truth", status: "" },
			{ item: "Integrity", meaning: "Living in alignment with values", status: "" },
			{ item: "Self-acceptance", meaning: "Welcoming all parts of myself", status: "" },
			{ item: "Self-care", meaning: "Tending to my own needs", status: "" },
			{ item: "Self-connection", meaning: "Awareness of inner experience", status: "" },
			{ item: "Self-knowledge", meaning: "Understanding myself", status: "" },
			{ item: "Self-realization", meaning: "Becoming who I am meant to be", status: "" },
			{ item: "Mattering to myself", meaning: "Recognizing my own value", status: "" },
		],
		Understanding: [
			{ item: "Understanding", meaning: "Grasp what something means", status: "" },
			{ item: "Awareness", meaning: "Conscious presence", status: "" },
			{ item: "Clarity", meaning: "Clear thinking and perception", status: "" },
			{ item: "Discovery", meaning: "Finding or uncovering something new", status: "" },
			{ item: "Learning", meaning: "Gaining knowledge or insight", status: "" },
			{ item: "Making sense of life", meaning: "Understanding the bigger picture", status: "" },
			{ item: "Stimulation", meaning: "Mental engagement and interest", status: "" },
		],
		Meaning: [
			{ item: "Meaning", meaning: "A sense that something matters", status: "" },
			{ item: "Challenge", meaning: "Opportunities to stretch and grow", status: "" },
			{ item: "Aliveness", meaning: "Feeling fully vibrant and present", status: "" },
			{ item: "Consciousness", meaning: "Deep awareness of self and life", status: "" },
			{ item: "Contribution", meaning: "Making a difference", status: "" },
			{ item: "Effectiveness", meaning: "Capacity to bring about change", status: "" },
			{ item: "Exploration", meaning: "Willingness to investigate and try", status: "" },
			{ item: "Integration", meaning: "Wholeness and coherence", status: "" },
			{ item: "Purpose", meaning: "Having meaningful direction", status: "" },
		],
		Transcendence: [
			{ item: "Beauty", meaning: "Appreciating harmony and elegance", status: "" },
			{ item: "Celebration of life", meaning: "Honoring what’s precious", status: "" },
			{ item: "Communion", meaning: "Deep spiritual or emotional connection", status: "" },
			{ item: "Faith", meaning: "Trust in something greater", status: "" },
			{ item: "Flow", meaning: "Being fully absorbed in the moment", status: "" },
			{ item: "Hope", meaning: "Belief in possibilities", status: "" },
			{ item: "Inspiration", meaning: "Being uplifted into vision or action", status: "" },
			{ item: "Mourning", meaning: "Honoring loss with care", status: "" },
			{ item: "Peace (internal)", meaning: "Calm within", status: "" },
			{ item: "Presence", meaning: "Fully here and now", status: "" },
		],
	},

	Freedom: {
		Autonomy: [
			{ item: "Autonomy", meaning: "Make decisions without external control", status: "" },
			{ item: "Choice", meaning: "Freedom to decide", status: "" },
			{ item: "Ease", meaning: "Freedom from strain or effort", status: "" },
			{ item: "Independence", meaning: "Self-reliance and agency", status: "" },
			{ item: "Agency", meaning: "Ability to influence", status: "" },
			{ item: "Self-responsiblity", meaning: "Owning my own choices", status: "" },
			{ item: "Space", meaning: "Room to be and act", status: "" },
			{ item: "Spontaneity", meaning: "Freedom to act in the moment", status: "" },
		],
		"Leisure/Relaxation": [
			{ item: "Humour", meaning: "Lightness and laughter", status: "" },
			{ item: "Joy", meaning: "Delight and happiness", status: "" },
			{ item: "Play", meaning: "Fun, imagination and creativity", status: "" },
			{ item: "Pleasure", meaning: "Enjoyable sensations or experiences", status: "" },
			{ item: "Rejuvenation", meaning: "Feeling refreshed and renewed", status: "" },
		],
	},
};

export default needsData;
