const needsData = {
	"Subsistence and Security": {
		"Physical sustenance": [
			"Physical sustenance",
			"Air",
			"Food",
			"Health",
			"Movement",
			"Physical Safety",
			"Rest / sleep",
			"Shelter",
			"Touch",
			"Water",
		],
		Security: [
			"Security",
			"Consistency",
			"Order/Structure",
			"Peace (external)",
			"Peace of mind",
			"Protection",
			"Safety (emotional)",
			"Stability",
			"Trusting",
		],
	},
	Connection: {
		Affection: [
			"Affection",
			"Appreciation",
			"Attention",
			"Closeness",
			"Companionship",
			"Harmony",
			"Intimacy",
			"Love",
			"Nurturing",
			"Sexual expression",
			"Support",
			"Tenderness",
			"Warmth",
		],
		"To matter": [
			"To matter",
			"Acceptance",
			"Care",
			"Compassion",
			"Consideration",
			"Empathy",
			"Respect",
			"To be heard, seen",
			"To be known, understood",
			"To be trusted",
			"Understanding others",
			"Mutual Recognition",
			"Kindness",
		],
		Community: [
			"Community",
			"Belonging",
			"Communication",
			"Cooperation",
			"Equality",
			"Inclusion",
			"Mutuality",
			"Participation",
			"Partnership",
			"Self-expression",
			"Sharing",
		],
	},
	Meaning: {
		"Sense of self": [
			"Sense of self",
			"Authenticity",
			"Competence",
			"Creativity",
			"Dignity",
			"Growth",
			"Healing",
			"Honesty",
			"Integrity",
			"Self-acceptance",
			"Self-care",
			"Self-connection",
			"Self-knowledge",
			"Self-realizatioin",
			"Mattering to myself",
		],
		Understanding: [
			"Understanding",
			"Awareness",
			"Clarity",
			"Discovery",
			"Learning",
			"Making sense of life",
			"Stimulation",
		],
		Meaning: [
			"Meaning",
			"Challenge",
			"Aliveness",
			"Consciousness",
			"Contribution",
			"Creativity",
			"Effectiveness",
			"Exploration",
			"Integration",
			"Purpose",
		],
		Transcendence: [
			"Transcendence",
			"Beauty",
			"Celebration of life",
			"Communion",
			"Faith",
			"Flow",
			"Hope",
			"Inspiration",
			"Mourning",
			"Peace (internal)",
			"Presence",
		],
	},
	Freedom: {
		Autonomy: ["Autonomy", "Choice", "Ease", "Independence", "Power", "Self-responsiblity", "Space", "Spontaneity"],
		"Leisure/Relaxation": ["Leisure/Relaxation", "Humour", "Joy", "Play", "Pleasure", "Rejuvenation"],
	},
};

export default needsData;
